/************ Copyright Krono-Safe S.A. 2020, All rights reserved ************/

#include "suite.h"
#include <libpsy.h>

static unsigned int _current_idx = 0u;

/* The contents of this data structure were initially generated by the
 * script `scripts/gen-test.py`. */
static const struct g_control _test_suite[] =
{
  [0] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [1] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [2] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [3] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [4] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [5] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [6] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [7] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [8] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [9] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [10] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [11] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [12] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [13] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [14] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [15] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [16] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [17] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [18] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [19] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [20] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [21] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [22] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [23] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [24] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [25] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [26] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [27] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [28] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [29] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [30] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [31] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [32] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [33] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [34] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [35] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [36] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [37] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [38] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [39] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [40] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [41] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [42] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [43] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [44] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [45] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [46] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [47] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [48] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [49] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [50] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [51] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [52] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [53] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [54] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [55] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [56] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [57] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [58] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [59] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [60] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [61] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [62] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [63] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [64] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [65] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [66] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [67] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [68] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [69] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [70] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [71] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [72] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [73] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [74] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [75] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [76] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [77] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [78] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [79] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [80] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [81] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [82] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [83] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [84] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [85] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [86] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [87] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [88] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [89] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [90] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [91] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [92] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [93] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [94] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [95] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [96] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [97] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [98] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [99] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [100] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [101] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [102] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [103] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [104] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [105] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [106] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [107] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [108] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [109] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [110] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [111] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [112] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [113] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [114] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [115] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [116] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [117] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [118] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [119] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [120] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [121] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [122] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [123] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [124] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [125] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [126] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [127] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [128] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [129] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [130] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [131] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [132] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [133] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [134] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [135] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [136] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [137] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [138] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [139] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [140] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [141] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [142] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [143] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [144] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [145] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [146] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [147] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [148] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [149] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [150] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [151] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [152] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [153] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [154] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [155] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [156] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [157] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [158] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [159] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [160] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [161] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [162] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [163] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [164] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [165] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [166] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [167] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [168] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [169] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [170] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [171] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [172] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [173] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [174] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [175] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [176] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [177] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [178] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [179] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [180] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [181] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [182] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [183] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [184] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [185] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [186] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [187] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [188] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [189] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [190] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [191] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [192] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [193] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [194] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [195] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [196] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [197] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [198] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [199] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [200] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [201] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [202] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [203] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [204] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [205] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [206] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [207] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [208] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [209] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [210] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [211] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [212] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [213] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [214] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [215] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [216] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [217] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [218] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [219] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [220] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [221] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [222] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [223] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [224] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [225] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [226] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [227] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [228] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [229] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [230] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [231] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [232] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [233] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [234] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [235] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [236] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [237] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [238] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [239] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [240] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [241] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [242] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [243] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [244] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [245] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [246] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [247] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [248] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [249] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [250] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [251] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [252] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [253] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [254] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [255] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [256] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [257] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [258] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [259] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [260] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [261] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [262] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [263] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [264] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [265] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [266] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [267] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [268] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [269] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [270] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [271] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [272] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [273] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [274] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [275] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [276] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [277] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [278] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [279] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [280] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [281] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [282] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [283] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [284] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [285] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [286] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [287] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [288] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [289] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [290] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [291] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [292] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [293] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [294] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [295] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [296] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [297] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [298] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [299] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [300] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [301] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [302] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [303] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [304] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [305] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [306] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [307] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [308] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [309] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [310] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [311] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [312] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [313] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [314] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [315] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [316] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [317] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [318] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [319] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [320] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [321] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [322] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [323] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [324] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [325] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [326] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [327] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [328] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [329] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [330] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [331] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [332] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [333] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [334] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [335] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [336] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [337] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [338] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [339] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [340] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [341] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [342] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [343] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [344] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [345] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [346] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [347] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [348] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [349] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [350] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [351] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [352] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [353] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [354] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [355] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [356] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [357] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [358] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [359] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [360] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [361] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [362] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [363] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [364] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [365] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [366] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [367] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [368] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [369] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [370] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [371] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [372] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [373] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [374] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [375] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [376] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [377] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [378] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [379] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [380] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [381] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [382] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [383] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [384] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [385] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [386] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [387] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [388] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [389] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [390] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [391] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [392] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [393] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [394] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [395] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [396] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [397] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [398] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [399] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [400] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [401] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [402] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [403] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [404] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [405] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [406] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [407] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [408] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [409] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [410] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [411] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [412] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [413] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [414] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [415] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [416] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [417] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [418] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [419] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [420] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [421] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [422] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [423] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [424] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [425] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [426] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [427] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [428] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [429] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [430] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [431] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [432] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [433] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [434] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [435] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [436] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [437] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [438] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [439] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [440] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [441] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [442] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [443] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [444] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [445] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [446] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [447] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [448] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [449] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [450] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [451] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [452] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [453] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [454] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [455] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [456] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [457] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [458] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [459] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [460] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [461] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [462] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [463] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [464] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [465] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [466] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [467] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [468] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [469] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [470] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [471] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [472] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [473] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [474] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [475] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [476] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [477] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [478] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [479] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [480] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [481] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [482] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [483] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [484] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [485] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [486] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [487] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [488] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [489] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [490] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [491] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 2,
  },
  [492] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [493] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [494] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [495] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [496] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [497] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 2,
  },
  [498] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [499] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [500] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 1,
  },
  [501] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 0,
  },
  [502] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [503] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [504] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [505] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [506] = {
    .work_iterations = 7,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [507] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 1,
    .switch_value = 3,
  },
  [508] = {
    .work_iterations = 6,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
  [509] = {
    .work_iterations = 4,
    .cond_g14_or_g15 = 0,
    .switch_value = 3,
  },
  [510] = {
    .work_iterations = 3,
    .cond_g14_or_g15 = 0,
    .switch_value = 1,
  },
  [511] = {
    .work_iterations = 5,
    .cond_g14_or_g15 = 1,
    .switch_value = 0,
  },
};

const struct g_control *get_next_stimulus_for_g(void)
{
  const struct g_control *const val = &_test_suite[_current_idx];
  _current_idx = (_current_idx + 1u) % (sizeof(_test_suite) / sizeof(_test_suite[0]));
  return val;
}
